name: PlayerNotes
version: 2.0
description: Plugin for tracking notes on players.
author: blha303
website: http://blha303.com.au/PlayerNotes
main: me.blha303.PlayerNotes
commands:
    pnotesview:
        description: 'Show notes about a player. (/pnv)'
        usage: /pnotesview playername
        aliases: pnv
    pnotesadd:
        description: 'Add note. (/pna)'
        usage: /pnotesadd playername note
        aliases: pna
    pnotesposted:
        description: 'Show notes from a player. (/pnp)'
        usage: /pnotesposted playername
        aliases: pnp
permissions:
    playernotes.*:
        description: Allows players to use all pnotes commands
        children:
            playernotes.pnv: true
            playernotes.pna: true
            playernotes.pnp: true
    playernotes.pnv:
        description: Allows players to use /pnotesview
        default: false
    playernotes.pna:
        description: Allows players to use /pnotesadd
        default: false
    playernotes.pnp:
        description: Allows players to use /pnotesposted
        default: false